# -*- coding: utf-8 -*-
"""Bosques_Aleatorios_Embebido2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1llga4efSnKbwr-Iklrmv-F4sV6i_5DnF
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, KFold,GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, make_scorer
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import pearsonr
from sklearn.model_selection import StratifiedShuffleSplit
import seaborn as sns
#Carga de base de datos
datos = pd.read_csv(r"C:\Users\myria\Documents\CodigoFuenteTesis\datos\Glucosa_Data_Base_Clean.csv")
print(datos.info())
print(datos.head())

#Limpieza de datos
datos_clean=datos.dropna()
print(datos_clean.info())
print(datos_clean.head())

X= datos.drop(columns=['Glucosa'])
y=datos['Glucosa']


#Separación de caracteristicas y objetivo
X = datos_clean.drop('Glucosa', axis=1) # Todas las columnas
y = datos_clean['Glucosa'] #Columna de glucosa

X.columns =(
    X.columns
    .str.strip() # quita espacios al inicio/fin
    .str.lower() # pasa todo a minúsculas
    .str.normalize('NFKD') # elimina acentos
    .str.encode('ascii', errors='ignore')
    .str.decode('utf-8')
)
# Paso 1: Train (70%) y temp (30%)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=126, stratify=pd.qcut(y, q=10, duplicates='drop')
)

# Paso 2: Valid (15%) y Test (15%) desde temp
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=126,
    stratify=pd.qcut(y_temp, q=10, duplicates= 'drop')
)


# Scorer robusto para Pearson
def pearson_scorer(y_true, y_pred):
    try:
        r = pearsonr(y_true, y_pred)[0]
        return 0.0 if np.isnan(r) else r
    except:
            return 0.0

scorer_pearson = make_scorer(pearson_scorer, greater_is_better=True)

param_grid = {
    'n_estimators': [100, 200, 300], # más árboles para estabilidad
    'max_depth': [18, 25, None], # profundidad mayor o ilimitada
    'min_samples_split': [2, 5, 10], # control de división
    'min_samples_leaf': [1, 2, 4], # tamaño mínimo de hoja
    'max_features': ['sqrt', 'log2'] # selección de features
    }

modelo_rf= RandomForestRegressor (
    n_estimators=100,
    max_depth=18,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features='sqrt',
    bootstrap=True,
    criterion='squared_error',
    n_jobs=-1,
    random_state=126
)

print("\n Validación Cruzada")
kfold = KFold(n_splits=5, shuffle=True, random_state=126)

grid_search = GridSearchCV(
    estimator=modelo_rf,
    param_grid=param_grid,
    cv=kfold,
    scoring={'MAE':'neg_mean_absolute_error', 'Pearson':scorer_pearson},
    refit='Pearson', # selecciona el mejor modelo según Pearson
    n_jobs=-1,
    verbose=2
    )

grid_search.fit(X_train, y_train)

print("\n✅ Mejores hiperparámetros encontrados (según Pearson):")
print(grid_search.best_params_)
print("Mejor Pearson en validación:", grid_search.best_score_)

best_rf = grid_search.best_estimator_
best_rf.fit(X_train, y_train)

y_pred_train = best_rf.predict(X_train)
print("\n📊 Métricas en TRAIN con mejores hiperparámetros")
print("MAE:", mean_absolute_error(y_train, y_pred_train))
print("MSE:", mean_squared_error(y_train, y_pred_train))
print("R2:", r2_score(y_train, y_pred_train))
print("Pearson:", pearsonr(y_train, y_pred_train)[0])

y_pred_val = best_rf.predict(X_val)
print("\n📊 Métricas en VAL con mejores hiperparámetros")
print("MAE:", mean_absolute_error(y_val, y_pred_val))
print("MSE:", mean_squared_error(y_val, y_pred_val))
print("R2:", r2_score(y_val, y_pred_val))
print("Pearson:", pearsonr(y_val, y_pred_val)[0])

y_pred_test = best_rf.predict(X_test)
print("\n📊 Métricas en TEST con mejores hiperparámetros")
print("MAE:", mean_absolute_error(y_test, y_pred_test))
print("MSE:", mean_squared_error(y_test, y_pred_test))
print("R2:", r2_score(y_test, y_pred_test))
print("Pearson:", pearsonr(y_test, y_pred_test)[0])
# Verificar criterios

if pearsonr(y_test, y_pred_test)[0] >= 0.9 and mean_absolute_error(y_test, y_pred_test) <= 10:
  print("\n✅ El modelo cumple con los criterios de calidad (Pearson > 0.9 y MAE < 10)")
else:
    print("\n⚠️ El modelo NO cumple completamente los criterios.")


# Importancia de las características
importancias = best_rf.feature_importances_

# Crear un DataFrame ordenado
importancias_df = pd.DataFrame({
    'feature': X_train.columns,
    'importance': importancias
}).sort_values(by='importance', ascending=False)

print("\n📊 Importancia de las características:")
print(importancias_df)

# Gráfica de barras
plt.figure(figsize=(20,8))
importancias_df.plot(kind='bar', x='feature', y='importance', legend=False)
#plt.title("Importancia de las características en RandomForest")
plt.xlabel("Características", fontsize=14)
plt.ylabel("Importancia", fontsize=14)

plt.xticks(fontsize=10)
plt.yticks(fontsize=10)

plt.xticks
plt.tight_layout()
plt.savefig("C:/Users/myria/Documents/CodigoFuenteTesis/resultados/BosquesAleatorios/AnalisisImportanciasBAH.pdf"
, format="pdf", bbox_inches="tight")

#Gráfica de distribución de diferencias del modelo de bosques aleatorios del set de prueba. 

# Valores reales y predicciones del set de prueba
y_true = y_test.values
y_pred = y_pred_test

# Calcular diferencias
diff_values = y_true - y_pred


# Histograma de diferencias
plt.figure(figsize=(7,5))
plt.hist(diff_values, bins=20, edgecolor='black', alpha=0.7)
#plt.title("Histograma de diferencias")
plt.xlabel("Diferencia (referencia de glucosa - estimación de glucosa)[mg/dL]")
plt.ylabel("Frecuencia")
plt.grid(True, linestyle="--", alpha=0.7)

plt.savefig("C:/Users/myria/Documents/CodigoFuenteTesis/resultados/BosquesAleatorios/bland_altman_test_diferencias_BA.pdf", format="pdf", bbox_inches="tight")


# Q-Q plot
import scipy.stats as stats
plt.figure(figsize=(7,5))
stats.probplot(diff_values, dist="norm", plot=plt)
plt.title("Q-Q plot de diferencias")
plt.grid(True, linestyle="--", alpha=0.7)


# Test de Shapiro-Wilk
stat, p = stats.shapiro(diff_values)
print("Estadístico Shapiro-Wilk:", stat)
print("p-value:", p)

if p > 0.05:
    print("No se rechaza la normalidad (las diferencias son aproximadamente normales).")
else:
    print("Se rechaza la normalidad (las diferencias no siguen distribución normal).")


#Generar predicciones para train, val y test
y_train_pred = best_rf.predict(X_train).flatten()
y_val_pred = best_rf.predict(X_val).flatten()
y_test_pred = best_rf.predict(X_test).flatten()



#Función para calcular Pearson y evitar errores si hay
def calculate_pearson(y_true, y_pred):

    y_true = np.asarray(y_true).flatten()
    y_pred = np.asarray(y_pred).flatten()

    if y_true.size == 0 or y_pred.size == 0 or not np.isfinite(y_true).all() or not np.isfinite(y_pred).all():
        return np.nan

    correlation, _ = pearsonr(y_true, y_pred)
    return correlation
def print_metrics(y_true, y_pred, set_name):
  mae = mean_absolute_error(y_true, y_pred)
  mse = mean_squared_error(y_true, y_pred)
  R2 = r2_score(y_true, y_pred)
  r_value, _ = pearsonr(y_true, y_pred)
  print(f"{set_name}:")
  print(f"  MAE: {mae:.4f}")
  print(f"  MSE: {mse:.4f}")
  print(f"  R2: {R2:.4f}")
  print(f"  R: {r_value:.4f}")


print_metrics(y_train, y_train_pred, "Entrenamiento")
print_metrics(y_val, y_val_pred, "Validación")
print_metrics(y_test, y_test_pred, "Prueba")


    #Calcular Pearson para cada conjunto
pearson_train = calculate_pearson(y_train, y_train_pred)
pearson_test = calculate_pearson(y_test, y_test_pred)
pearson_val = calculate_pearson(y_val, y_val_pred)

print(f"Pearson Train: {pearson_train:.4f}")
print(f"Pearson Val: {pearson_val:.4f}")
print(f"Pearson Test: {pearson_test:.4f}")



# Predicciones en cada conjunto
y_train_pred = best_rf.predict(X_train).flatten()
y_val_pred   = best_rf.predict(X_val).flatten()
y_test_pred  = best_rf.predict(X_test).flatten()


# Función para graficar regresión
def plot_regression(y_true, y_pred, filename):
    plt.figure(figsize=(6,6))
    sns.scatterplot(x=y_true, y=y_pred, alpha=0.6, edgecolor="k")
    # Línea de identidad
    lims = [min(y_true.min(), y_pred.min()), max(y_true.max(), y_pred.max())]
    plt.plot(lims, lims, 'r--', lw=2, label="Línea identidad")
    plt.xlabel("Glucosa de referencia [mg/dL]")
    plt.ylabel("Predicciones")
    plt.legend()
    plt.grid(True, linestyle="--", alpha=0.7)
    plt.savefig(filename, format="pdf", bbox_inches="tight")
    plt.close()

# Graficar cada conjunto
plot_regression(y_train, y_train_pred,"C:/Users/myria/Documents/CodigoFuenteTesis/resultados/BosquesAleatorios/regresion_train.pdf")
plot_regression(y_val, y_val_pred,"C:/Users/myria/Documents/CodigoFuenteTesis/resultados/BosquesAleatorios/regresion_val.pdf")
plot_regression(y_test, y_test_pred,"C:/Users/myria/Documents/CodigoFuenteTesis/resultados/BosquesAleatorios/regresion_test.pdf")

#Gráfica de la norma ISO 15197:2015 para set de prueba
x = y_test  # Glucosa medida [mg/dL]
y = y_test - y_test_pred  # Diferencia estimado - medido [mg/dL]
val_max = np.max(x)

# Crear figura y ejes
fig, ax = plt.subplots(figsize=(6, 6))

# Gráfica de dispersión con estilo
ax.scatter(x, y,
           color='royalblue',
           edgecolor='black',
           alpha=0.7,
           s=60,
           label='Predicciones')

# Límites ISO 15197:2015
x = np.linspace(0, 200, 200)

# Para glucosa < 100 mg/dL → ±15 mg/dL
ax.plot([0, 100], [15, 15], 'r--', linewidth=1.5)
ax.plot([0, 100], [-15, -15], 'r--', linewidth=1.5)

# Para glucosa ≥ 100 mg/dL → ±15% del valor medido
ax.plot([100, 200], [15, 200*0.15], 'r--', linewidth=1.5)
ax.plot([100, 200], [-15, -200*0.15], 'r--', linewidth=1.5)

# Ajustes de aspecto
ax.set_xlim(0, 200)
ax.set_ylim(-40, 40)  # rango de diferencias
ax.set_xlabel('Glucosa de referencia [mg/dL]', fontsize=12)
ax.set_ylabel('Diferencia estimado - medido [mg/dL]', fontsize=12)

# Título con estilo
#ax.set_title('Norma ISO 15197:2015 (0–200 mg/dL)', fontsize=14, fontweight='bold')

# Cuadrícula más sutil
ax.grid(True, linestyle='--', alpha=0.5)

# Leyenda
#ax.legend(loc='upper right', frameon=True)

# Mostrar
plt.tight_layout()
plt.savefig("C:/Users/myria/Documents/CodigoFuenteTesis/resultados/BosquesAleatorios/norma_iso_test_BAHDRU41.pdf", format="pdf", bbox_inches="tight")


#Gráfica de Bland-Altman para el set de prueba

# Valores reales y predicciones del set de prueba
y_true = y_test.values
y_pred = y_test_pred

# Calcular medias y diferencias
mean_values = np.mean([y_true, y_pred], axis=0)
diff_values = y_true - y_pred

# Estadísticos
mean_diff = np.mean(diff_values)  # sesgo
std_diff = np.std(diff_values, ddof=1)  # desviación estándar
loa_upper = mean_diff + 1.96 * std_diff  # límite superior
loa_lower = mean_diff - 1.96 * std_diff  # límite inferior

# Gráfico Bland-Altman
plt.figure(figsize=(7,6))
plt.scatter(mean_values, diff_values, alpha=0.6, edgecolor="k")
plt.axhline(mean_diff, color='red', linestyle='--', label=f"Sesgo = {mean_diff:.2f}")
plt.axhline(loa_upper, color='blue', linestyle='--', label=f"Límite superior = {loa_upper:.2f}")
plt.axhline(loa_lower, color='blue', linestyle='--', label=f"Límite inferior = {loa_lower:.2f}")
plt.xlabel("Media entre valores reales y predicciones")
plt.ylabel("Diferencia (Real - Predicción)")
#pt.title("Gráfico de Bland-Altman (Test Set)")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.7)
plt.ylim(-40,40)


plt.savefig("C:/Users/myria/Documents/CodigoFuenteTesis/resultados/BosquesAleatorios/bland_altman_test_BAHDRU41.pdf", format="pdf", bbox_inches="tight")

